[package]
name = "casino-world"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
log = "0.4.25"
env_logger = "0.11.6"
tokio-tungstenite = "0.26.1"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
